#!/bin/bash

# Load scripting addition on Dock restart
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Configure yabai settings
displays=$(yabai -m query --displays | jq -r '.[].frame.w')

# Determine if the native display (MacBook Pro) is active
if [[ "$displays" == *"1512"* ]]; then
  # MacBook Pro's native display detected
  yabai -m config external_bar all:0:0
else
  # External display detected
  yabai -m config external_bar all:32:0
fi

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_focus_cycle off
yabai -m config window_zoom_persist off
yabai -m config window_placement second_child
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config window_gap 2

# Set layout to bsp
yabai -m config layout bsp

# Exclude problematic apps from being managed
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

# Add signal to focus the first window when the space is changed
yabai -m signal --add event=space_changed action="\
yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id')"

# Add signal to focus next window when a window is destroyed
yabai -m signal --add event=window_destroyed action="\
next_window_id=\$(yabai -m query --windows --space | jq 'map(select(.id != env.YABAI_WINDOW_ID)) | .[0].id' -r); \
if [ -n \"\$next_window_id\" ]; then \
  yabai -m window --focus \$next_window_id; \
fi"
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
