general.import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[debug]
persistent_logging = true

[env]
TERM = "alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[window]
blur = true
opacity = 0.75

padding.x = 0
padding.y = 0

decorations = "none"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux "]


[font]
normal.family = "BlexMono Nerd Font Mono"
bold.family = "BlexMono Nerd Font Mono"
italic.family = "BlexMono Nerd Font Mono"
bold_italic.family = "BlexMono Nerd Font Mono"

size = 18.0

[mouse]
hide_when_typing = true
